# Generated by Django 4.1 on 2022-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_topic_topicarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
