# Generated by Django 4.1 on 2022-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_topic_options_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.TopicArticle', to='articles.topic'),
        ),
    ]
