# Generated by Django 4.1 on 2022-08-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicarticle',
            old_name='main_topic',
            new_name='is_main',
        ),
    ]
