# Generated by Django 4.1 on 2022-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_main_topic_topicarticle_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='articles', through='articles.TopicArticle', to='articles.topic'),
        ),
    ]
